# Generated by Django 4.0.4 on 2022-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, upload_to='listing_images'),
        ),
    ]
