# Generated by Django 4.0.4 on 2022-07-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_watchlist_item_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
