# Generated by Django 4.0.4 on 2022-08-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_bid_amount_remove_bid_bidder_bid_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_exist',
            field=models.BooleanField(default=False),
        ),
    ]
